-- Alterar tabla productos para agregar los nuevos campos
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS codigo VARCHAR(20) UNIQUE,
ADD COLUMN IF NOT EXISTS id_categoria INTEGER REFERENCES categorias(id_categoria) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS largo_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS ancho_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS alto_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS diametro_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS fondo_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS altura_asiento_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS altura_cubierta_cm DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS peso_kg DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS material VARCHAR(100),
ADD COLUMN IF NOT EXISTS moneda CHAR(3) DEFAULT 'CLP',
ADD COLUMN IF NOT EXISTS incluye_iva BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS requiere_presupuesto BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS unidad_venta VARCHAR(50) DEFAULT 'unidad',
ADD COLUMN IF NOT EXISTS stock INTEGER,
ADD COLUMN IF NOT EXISTS foto_principal_url TEXT,
ADD COLUMN IF NOT EXISTS notas_especiales TEXT,
ADD COLUMN IF NOT EXISTS fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Modificar tipo del precio_unitario
ALTER TABLE productos
ALTER COLUMN precio_unitario DROP NOT NULL,
ALTER COLUMN precio_unitario TYPE NUMERIC(12,2);